### ISSUE TITLE
Error on initialization of Window class

### ISSUE THREAD

**Issue by MaxDerDeveloper** [davidmaamoaix/Overlay#1]
I'm initializing the overlay.Window class and get this error:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\test_overlay.py", line 3, in <module>
    win = Window()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\overlay\window.py", line 42, in __init__
    self.transparent = kwargs.get('transparent', False)
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python38\lib\site-packages\overlay\window.py", line 125, in transparent
    self._root.config(bg=bg)
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "systemWindowBody"

**Comment by linxuanm** [comment]
Hi.
It seems like you are trying to run the module on Windows (or other operating systems other than Mac OS), which isn't supported by this module.
There are other alternatives for creating a floating UI on Windows, such as using pywin32. Overlay was created due to the lack of such methods on Mac OS.

**Comment by MaxDerDeveloper** [comment]
Okay thanks dude

**Comment by elvirag** [comment]
You should not state that this works on Windows OS, because you said it wasn't tested, so now it is, and it doesn't work, so please remove the line that states that it works, wasn't tested.
Good work, though!

**Comment by linxuanm** [comment]
By "not tested" I meant that I am not sure if it would work. The platform section is a specification of the compatibility state of common platforms rather than a list of platforms on which this package functions.

However I do see your concern, and indeed, the current format is rather ambiguous. Thanks for the reminder.

**Comment by elvirag** [comment]
> By "not tested" I meant that I am not sure if it would work. The platform section is a specification of the compatibility state of common platforms rather than a list of platforms on which this package functions.
> 
> However I do see your concern, and indeed, the current format is rather ambiguous. Thanks for the reminder.

Thanks, and thank you for the change, keep up the good work!

**Comment by Heath123** [comment]
Uh, surely this shouldn't be closed before it gets fixed?

**Comment by linxuanm** [comment]
> Uh, surely this shouldn't be closed before it gets fixed?

It wasn't planned to be fixed, but now it is.
I'll keep this open until the fix is released.
