### ISSUE TITLE
_tkinter.TclError: unknown color name "1"

### ISSUE THREAD

**Issue by jcarlosroldan** [davidmaamoaix/Overlay#3]
When running any of the examples on Python 3.8 over Windows 10, I get the same "unknown color name" error.

When I run
```py
from overlay import Window

win = Window()
Window.launch()
```

I get
```sh
Traceback (most recent call last):
  File "D:\Desktop\test.py", line 3, in <module>
    win = Window()
  File "D:\ProgramData\Anaconda3\lib\site-packages\overlay\window.py", line 63, in __init__
    self._root.wm_attributes('-transparent', True)
  File "D:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1788, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: unknown color name "1"
```

**Comment by spinnelein** [comment]
Having the same issue.

**Comment by aleaforny** [comment]
Same issue also.

**Comment by rafaelurben** [comment]
Same issue here (Windows 10)

**Comment by hiiamtin** [comment]
in file window.py
change True //self._root.wm_attributes('-transparent', True)
to "name_of_color"
Ex
self._root.wm_attributes('-transparent', "white")
it's work for me

**Comment by j-h-m** [comment]
Same issue still

**Comment by j-h-m** [comment]
> in file window.py
> change True //self._root.wm_attributes('-transparent', True)
> to "name_of_color"
> Ex
> self._root.wm_attributes('-transparent', "white")
> it's work for me

same issue still, but this works

**Comment by Xyndra** [comment]
> in file window.py
> change True //self._root.wm_attributes('-transparent', True)
> to "name_of_color"
> Ex
> self._root.wm_attributes('-transparent', "white")
> it's work for me

It works for me too

**Comment by akisha009** [comment]
> > in file window.py
> > change True //self._root.wm_attributes('-transparent', True)
> > to "name_of_color"
> > Ex
> > self._root.wm_attributes('-transparent', "white")
> > it's work for me
> 
> It works for me too

 Where and what to replace? I am in window.py and I clicked Ctrl + F (find), and there is no "True //self._root.wm_attributes('-transparent', True)"

**Comment by rafaelurben** [comment]
@akisha009 
> Where and what to replace? I am in window.py and I clicked Ctrl + F (find), and there is no "True //self._root.wm_attributes('-transparent', True)"

You need to replace `self._root.wm_attributes('-transparent', True)` with `self._root.wm_attributes('-transparent', "white")` (= replace `True` with `"white"`)

https://github.com/davidmaamoaix/overlay/blob/ebfba98729d77a91e77777a514039abdb86c3e5b/overlay/window.py#L63

**Comment by catdogmat** [comment]
PR #8 will fix this
